# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 387b396d73497b8310394950a56b71baea70d218739e22f27e5890b655bcda0b1f260a318d1e76f4d1ac62817273539e5ec7d2679e07e6c2591872a2eeec2832

test:
  secret_key_base: a82a720dded15641ea62494dddeb3066a5d25756bc8a84998a13e7fbf9ba14e1c52090928786ec684890468c84b2ff77cdab659c1dfa1676252f5443ccda9be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
